<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://camel.apache.org/cxf/jaxws/dispatch" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:tns="http://camel.apache.org/cxf/jaxws/dispatch" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://camel.apache.org/cxf/jaxws/dispatch" xmlns:tns="http://camel.apache.org/cxf/jaxws/dispatch" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:element name="InvokeOneWay" nillable="true" type="xsd:anyType"/>
        </xsd:schema>
  </wsdl:types>
  <wsdl:message name="InvokeOneWay">
    <wsdl:part name="InvokeOneWayRequest" element="tns:InvokeOneWay">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="OneWay">
    <wsdl:operation name="InvokeOneWay">
      <wsdl:input name="InvokeOneWay" message="tns:InvokeOneWay">
    </wsdl:input>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="OneWayServiceSoapBinding" type="tns:OneWay">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
            <wsp:PolicyReference URI="#BN__binding"/>
        </wsp:Policy>
    <wsdl:operation name="InvokeOneWay">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="InvokeOneWay">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="service">
    <wsdl:port name="port" binding="tns:OneWayServiceSoapBinding">
      <soap:address location="https://p0204-iflmap.hcisbp.eu1.hana.ondemand.com:443/cxf/testflow"/>
    </wsdl:port>
  </wsdl:service>
    <wsp:UsingPolicy required="true" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"/>
    <wsp:Policy wsu:Id="BN__binding" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
        <wsp:ExactlyOne>
            <wsp:All>
                <sp:TransportBinding xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken>
                                    <wsp:Policy>
                                    <wsp:ExactlyOne>
                                    <sp:HttpBasicAuthentication/>
                                    <sp:RequireClientCertificate/>
                                    </wsp:ExactlyOne>
                                    </wsp:Policy>
                                </sp:HttpsToken>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <wsp:ExactlyOne>
                                    <sp:Basic256/>
                                    <sp:Basic192/>
                                    <sp:Basic128/>
                                    <sp:TripleDes/>
                                    <sp:Basic256Rsa15/>
                                    <sp:Basic192Rsa15/>
                                    <sp:Basic128Rsa15/>
                                    <sp:TripleDesRsa15/>
                                    <sp:Basic256Sha256/>
                                    <sp:Basic192Sha256/>
                                    <sp:Basic128Sha256/>
                                    <sp:TripleDesSha256/>
                                    <sp:Basic256Sha256Rsa15/>
                                    <sp:Basic192Sha256Rsa15/>
                                    <sp:Basic128Sha256Rsa15/>
                                    <sp:TripleDesSha256Rsa15/>
                                </wsp:ExactlyOne>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                    </wsp:Policy>
                </sp:TransportBinding>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
</wsdl:definitions>
